### PR TITLE
Clone elements using importNode to avoid reloading media

### PR DESCRIPTION
**Pull request by javan**
Using `cloneNode` on `<video>` and `<audio>` elements reloads their `src`, which causes unnecessary network requests.

Note what happens when navigating away from a page with a `<video>`.

Before (using `cloneNode`):
clonenode

After (using `importNode`):
importnode

### CODE REVIEW

**Comment by javan** [comment]
This prevented images from loading in FF after hitting the back button.
ff-back-images

**Comment by dhh** [comment]
Wonder if this isn't worth having two paths for. Big savings for the browsers that do support this. Maybe just not do it on FF?

**Comment by javan** [comment]
BC3 keeps the savings by removing the `src` attribute in TL snapshots and then adding it back: https://github.com/basecamp/bc3/blob/master/app/assets/javascripts/all/behaviors/page/disable_media_in_turbolinks_snapshots.coffee

I think something like that could move into TL itself.

**Comment by dhh** [comment]
👌

**Comment by javan** [comment]
For non-Basecampers, here's the source:
```coffee
elementNames = ["video", "audio", "iframe"]

enabledAttribute = "src"
disabledAttribute = "data-disabled-src"

[enabledSelector, disabledSelector] = do ->
  enabledSelectors = []
  disabledSelectors = []

  for elementName in elementNames
    enabledSelectors.push("#{elementName}[#{enabledAttribute}]")
    disabledSelectors.push("#{elementName}[#{disabledAttribute}]")

  [enabledSelectors.join(","), disabledSelectors.join(",")]

# Disable before Turbolinks takes a snapshot to avoid
# unnecessary network requests when the snapshot is loaded.
$(document).on "turbolinks:snapshot-save", ->
  $(enabledSelector).each ->
    $element = $(this)
    $element.attr(disabledAttribute, $element.attr(enabledAttribute))
    $element.removeAttr(enabledAttribute)

# Reenable on page load
$(document).on "turbolinks:load", ->
  $(disabledSelector).each ->
    $element = $(this)
    $element.attr(enabledAttribute, $element.attr(disabledAttribute))
    $element.removeAttr(disabledAttribute)
```

**Pull request closed without merging**
